ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ io.github.cbaumont.WebAppKt.module ]
    }
}

secrets {
    encryptKey = "00112233445566778899aabbccddeeff"
    encryptKey = ${?APP_ENCRYPT_KEY}
    signKey = "6819b57a326945c1968f45236589"
    signKey = ${?APP_SIGN_KEY}
}