name: Live check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest

    steps:
      - name: Call the app
        run: |
          curl -fsS -m 3 https://where-is-wordo.abacatogames.com
